name: 'Donut'
inputs:
  days:  # id of input
    description: 'Comma separated list of days of week to not run'
    required: true
    default: ''
  timezone:
    description: 'Timezone'
    default: 'America/New_York'
outputs:
  deploy:
    description: 'Should we deploy?'
runs:
  using: 'node12'
  main: 'dist/index.js'
