on:
  workflow_dispatch:

jobs:
  manual:
    runs-on: ubuntu-latest
    steps:
      - id: donut
        uses: kwngo/donut@main
        with:
          days: friday,sunday
      - name: Display output
        run: |
          echo ${{ steps.donut.outputs.deploy }}
      - name: Install dependency
        if: ${{ steps.donut.outputs.deploy == 'true' }}
        run: |
          echo 'Running installing dependency'
